package com.shopping.common

object Strings {
    const val AddToCart = "Add To Cart"
    const val Update = "Update"
    const val Create = "Create"
    const val City = "City"
    const val Cvc = "CVC"
    const val ExpirationDate = "Exp Date"
    const val Country = "Country"
    const val Number = "Number"
    const val Line = "Line"
    const val ZipCode = "Zip Code"
    const val CreateAddress = "Create Address"
    const val ChangePassword = "Change Password"
    const val Change = "Change"
    const val CurrentPassword = "Current Password"
    const val NewPassword = "New Password"
    const val Cards = "Cards"
    const val Addresses = "Addresses"
    const val Orders = "Orders"
    const val Settings = "Settings"
    const val AlreadyMember = "Already member?"
    const val DontHaveAccount = "Don't have account?"
    const val WebsiteName = "Shopally"
    const val EditProfile = "Edit Profile"
    const val Search = "Search"
    const val SignOut = "Sign Out"
    const val DeleteAccount = "Delete Account"
    const val Cart = "Cart"
    const val CreateCard = "Create Card"
    const val Home = "Home"
    const val Profile = "Profile"
    const val SignIn = "Sign In"
    const val SignUp = "Sign Up"
    const val Email = "Email"
    const val Name = "Name"
    const val Password = "Password"
    const val PasswordHelperText = "Password must contain at least 8 characters and 1 number"
}